# Generated by Django 4.2.7 on 2023-12-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_4_app', '0002_bookborrowing_group_librarycard_literature_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(),
        ),
    ]
